CEXDIR=ccex/
ASMDIR=ccex3a/
LIBDIR=lib/

all :
	cd $(CEXDIR) && make
	cd $(ASMDIR) && make
	cd $(LIBDIR) && make

clean :
	cd $(CEXDIR) && make clean
	cd $(ASMDIR) && make clean
	cd $(LIBDIR) && make clean
